package com.mycompany.guardatupasss;
// Generated 26-may-2016 18:31:56 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String clave;

    public Usuario() {
    }

	
    public Usuario(String nombre) {
        this.nombre = nombre;
    }
    public Usuario(String nombre, String clave) {
       this.nombre = nombre;
       this.clave = clave;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


